<?php

/*
 * Implementation of hook_init().
 */
function eduglu_about_init() {
  drupal_add_css(drupal_get_path('module', 'eduglu_about') . "/eduglu_about.css");
}

/*
 * Implementation of hook_menu().
 */
function eduglu_about_menu() {
  $items['about-group'] = array(
    'title' => 'About Group',
    'description' => t('Shows top contributors and recent activity in a group.'),
    'page callback' => 'eduglu_about_page',
    'access arguments' => array('access content'),
  );

  return $items;
}

function eduglu_about_page() {
  // Set context
  if ($space = spaces_get_space()) {
    $options = eduglu_about_flot_options();

  $result = db_query("SELECT
    count(date_format(from_unixtime(created), '%Y%U')) as count,
    date_format(from_unixtime(created), '%U') as week,
    created as sortdate
    FROM {node}
    WHERE type in ('story','poll','event_cck','event','job_form','wiki','learning_contract','quiz','blog')
    GROUP BY date_format(from_unixtime(created), '%Y%U')
    ORDER BY sortdate desc
    LIMIT 54");


  $data = _metrics_dashboard_process_weekly($result);
  
    // Members added by week.
    $d1 = new flotData($data);

    return "<div class='grid-3 about-group-legend'>300 Members</div>" . "<div class='grid-10'>" . theme('flot_graph', array('style'=>'height:50px;width:500px;'), array($d1), $options) . "</div>";
  }
  else {
    return "";
  }
}

function eduglu_about_flot_options() {
  $options->colors = array('#E4E4E4');
  $options->bars->show = true;
  $options->bars->barWidth = .7;
  $options->bars->fill = 1;
  $options->grid = array(borderWidth=>0, tickColor=>'white');
  $options->xaxis = array('ticks'=>array());
//  $options->yaxis = array('ticks'=>array());
  return $options;
}


/*
 * Helper function to align week numbers amongst multiple years.
 */
function _metrics_dashboard_correct_weeks($weeks_array) {
  $keys = array_keys($weeks_array);
  for ($i = 0; $i <= count($keys); $i++) {
    if ($keys[$i] < $keys[$i + 1]) {
      for ($p = $i; $p >= 0; $p--) {
        $keys[$p] = $keys[$p] + 53;
      }
      break;
    }
  }

  return array_combine($keys, $weeks_array);
}

/*
 *  Helper function. Process weekly stats.
 */
function _metrics_dashboard_process_weekly($result) {
  $results = array();
  // Pull out into keyed array.
  while ($data = db_fetch_array($result)) {
    $results[$data['week']] = intval($data['count']);
  }
  $results = _metrics_dashboard_correct_weeks($results);

  ksort($results);

// Fill in empty values with zeros.
  $keys = array_keys($results);
 
  $end = array_pop($keys);
  $values = array();
  for ($i = $keys[0]; $i <= $end; $i++) {
    if ($results[$i]) {
      $values[] = $results[$i];
    }
    else {
      $values[] = 0;
    }
  }
  
  // Convert to format required for flot
  $flot_values = array();
  foreach ($values as $key => $value) {
    $flot_values[$key] = array(0 => $key, 1 => $value);
  }

  return $flot_values;
}
