<?php
// TODO cache everything for 24 hours.
// Move stuff into theme functions
include_once('eduglu_about.features.inc');

/*
 * Implementation of hook_init().
 */
function eduglu_about_init() {
  drupal_add_css(drupal_get_path('module', 'eduglu_about') . "/eduglu_about.css");
  drupal_add_js(drupal_get_path('module', 'eduglu_about') . "/eduglu_about.js");
}

/*
 * Implementation of hook_menu().
 */
function eduglu_about_menu() {
  $items['about'] = array(
    'title' => 'About',
    'description' => t('Shows top contributors and recent activity in a group.'),
    'page callback' => 'eduglu_about_page',
    'access callback' => 'spaces_access_feature',
    'access arguments' => array('view', 'eduglu_about'),
    'menu_name' => 'features',
    'file' => 'eduglu_about_page.inc',
    'weight' => -1000,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['about/group'] = array(
    'title' => "About Group",
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  return $items;
}

/*
 * Implementation of hook_theme().
 */
function eduglu_about_theme() {
  return array(
    'eduglu_about_page' => array(
      'arguments' => array('space' => array()),
      'file' => 'eduglu_about_theme.inc',
    ),
    'eduglu_about_stats_boxes_container' => array(
      'arguments' => array('space' => array()),
      'file' => 'eduglu_about_theme.inc',
    ),
    'eduglu_about_top_contributor' => array(
      'arguments' => array('uid' => array(), 'top_posters' => array(), 'top_commenters' => array()),
      'file' => 'eduglu_about_theme.inc',
    ),
    'eduglu_about_top_contributor_box' => array(
      'arguments' => array('top_contributors' => array(), 'top_posters' => array(), 'top_commenters' => array()),
      'file' => 'eduglu_about_theme.inc',
    ),
    'eduglu_members_listing' => array(
      'arguments' => array('members' => array(), 'num_members' => array()),
      'file' => 'eduglu_about_theme.inc',
    ),
    'eduglu_stats_box' => array(
      'arguments' => array('flotData' => array(), 'options' => array(), 'label' => array(), 'legend' => array()),
      'file' => 'eduglu_about_theme.inc',
    ),
  );
}
