<?php

include_once('eduglu_core.features.inc');

/**
 * Implementation of hook_menu().
 */
function eduglu_core_menu() {
  $items['eduglu_front_page_redirect'] = array(
    'title' => "redirecting...",
    'description' => t('Just a handy redirect tool'),
    'page callback' => 'eduglu_core_redirect',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Redirect authenticated users to their dashboard away from the welcome page.
 */
function eduglu_core_redirect() {
  global $user;
  if ($user->uid == 0) {
    drupal_goto("welcome");
  }
  else {
    drupal_goto("dashboard");
  }
}

/**
 * Implementation of hook_menu_alter().
 */
function eduglu_core_menu_alter(&$items) {
  // Kill undesirable menu items
  $yank = array(
    'book',
    'rss.xml',
    'node/%node/outline',
  );
  foreach ($yank as $path) {
    if (!empty($items[$path])) {
      unset($items[$path]);
    }
  }
}

function eduglu_core_form_alter(&$form, &$form_state, $form_id) {
//dpm($form_id);
//dpm($form);
//dpm($form_state);
  switch ($form_id) {
    // Redirect people to dashboard after logging in from the front page.
    case 'user_login_block':
      $form['#action'] = url("welcome", array('query' => array('destination' => 'dashboard')));
      break;
  }
}

