<?php

include_once('eduglu_groups.features.inc');

/*
 * Impmentation of hook_init().
 */
function eduglu_groups_init() {
   drupal_add_js(drupal_get_path('module', 'eduglu_groups')
                 .'/eduglu_groups.js', 'module');
}

/*
 * Impmentation of hook_preprocess_page().
 */
function eduglu_groups_preprocess_page(&$vars, $hook) {
  // Create my groups div.
  $vars['my_groups'] = eduglu_groups_prepare_my_groups();
}

function eduglu_groups_prepare_my_groups() {
  global $user;
  
  $results = db_query("SELECT o.nid, n.title
                      FROM {og_uid} o
                      JOIN {node} n
                      WHERE o.nid = n.nid
                      AND o.uid = %d
                      AND o.is_active = 1", $user->uid);
  
  $groups = array();
  while ($data = db_fetch_array($results)) {
    $groups[$data['nid']] = $data['title'];
  }
  
  // Sort the groups.
  natcasesort($groups);
  $num_columns = 2;
  if (count($groups > 45)) {
    $num_columns = 3;
  }
  $length_column = count($groups) / 3 + 1; // Add one so no orphaned column at end.
  $chunked_groups = array_chunk($groups, $length_column, true);
  
  $output .= "<div id='my-groups'>";
  $output .= "<h2 class='grid-3'>My Groups</h2><p class='grid-5'>"
  . l("Browse all groups", "og/all", array('attributes' => array('class' => 'grid-2')))
  . l("Manage my subscriptions", "mailnode/subscriptions", array('attributes' => array('class' => 'grid-2')))
  . "<hr />";
  $output .= "<div class='clear-block'>";
  foreach ($chunked_groups as $groups) {
    $output .= "<div class='grid-4'>";
    foreach ($groups as $nid => $group_title) {
      $output .= l($group_title, "node/" . $nid);
    }
    $output .= "</div>";
  }
  $output .= "</div>";
  
  $output .= "<strong>" .
    l("Create new group", "node/add/group", array('attributes' => array('class' => 'grid-2 create-new-group')))
    . "</strong>";
  $output .= "</div>";  
  return $output;  
}