<?php

/**
 * Helper function to ensure a permission exists in a roles array for a given role/perm.
 */
function _eduglu_ensure_perm(&$roles, $role, $perm) {
  if (!isset($roles[$role]['perm']) || !in_array($perm, $roles[$role]['perm'])) {
    $roles[$role]['perm'][] = $perm;
  }
}

/**
 * Helper function to remove a permission from a roles array for a given role/perm.
 */
function _eduglu_remove_perm(&$roles, $role, $perm) {
  if (in_array($perm, $roles[$role]['perm'])) {
    $position = array_search($perm, $roles[$role]['perm']);
    unset($roles[$role]['perm'][$position]);
  }
}

/**
 * THEME & UI  FUNCTIONS ==============================================
 */

/**
 * Implementation of hook_theme_registry_alter().
 */
function eduglu_theme_registry_alter(&$theme_registry) {
  // Yank out og_preprocess_node.
  if ($key = array_search('og_preprocess_node', $theme_registry['node']['preprocess functions'])) {
    unset($theme_registry['node']['preprocess functions'][$key]);
  }
}