<?php

include_once('eduglue_discussion.features.inc');

/**
 * Implementation of hook_menu().
 */
function eduglue_discussion_menu() {
  $items = array();
  $items['discussion'] = array(
    'title' => 'Discussions',
    'page callback' => 'eduglue_discussion_discussion',
    'page arguments' => array(),
    'access callback' => 'spaces_feature_access',
    'access arguments' => array('eduglue_discussion'),
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
  );
}

/**
 * Empty page callback for discussion feature.
 */
function eduglue_discussion_discussion() {
  context_set('spaces', 'features', 'eduglue_discussion');
  return views_embed_view('og_ghp_ron_spaces');
}

/*
 * Implementation of hook_form_alter().
 */
function eduglue_discussion_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == "search_theme_form") {
    
    if (!isset($form['#submit'])) {
      $form['#submit'] = array('eduglue_discussion_search_submit');
    }
    else {
      $key = array_search('search_box_form_submit', $form['#submit']);
      if ($key !== FALSE) {
        // Replace the search module's function.
        $form['#submit'][$key] = 'eduglue_discussion_search_submit';
      }
    }
   

    // Spaces prefixes tend to 'drift'. Check if on user page and ignore
    // spaces if it still thinks we're in a group space. 
    $continue = false;

    (strpos($_GET['q'], 'user') === false) ? "" : $continue = true; 
    
    if ($space = spaces_get_space()) {
      if ($continue) {
       return;	
      }
      
      $form['#submit'] = array('eduglue_discussion_search_submit');
      
      $form['group_search'] = array(
        '#type' => 'checkbox',
        '#options' => t('Enable'),
        '#description' => t('Search this group'),
        '#default_value' => true,
      );
      $form['gid'] = array(
        '#type' => 'value',
        '#value' => $space->sid,
      );
      //dpm($form);
      //dpm($form_state);
    }
  }
  
}

function eduglue_discussion_search_submit($form, &$form_state) {
  $form_id = $form['form_id']['#value'];
  $keys = $form_state['values'][$form_id];
  // Handle Apache webserver clean URL quirks.
  if (variable_get('clean_url', '0')) {
    $keys = str_replace('+', '%2B', $keys);
  }
  
  if ($form['group_search']['#value']) {
    $group_nid = $form_state['values']['gid'];
//    dpm($group_nid);
 //   dpm($keys);
    $form_state['redirect'] = array("search/apachesolr_search/" .
      trim($keys), "filters=im_og_gid%3A" . $group_nid . "&retain-filters=1");    
  }
  else {
    $form_state['redirect'] = "search/apachesolr_search/" . trim($keys);
  }

}
