<?php

include_once('eduglu_quiz.features.inc');

/**
 * Implementation of hook_menu().
 */
function eduglu_quiz_menu() {
  $items = array();
  $items['quiz'] = array(
    'title' => 'Quizzes',
    'page callback' => 'eduglu_quiz_recent',
    'page arguments' => array(),
    'access arguments' => array('view', 'eduglu_quiz'),
    'access callback' => 'spaces_access_feature',
    'type' => MENU_NORMAL_ITEM,
    'menu_name' => 'features',
  );
  
  return $items;
}

function eduglu_quiz_recent() {
  return views_embed_view('eduglu_latest_quizzes', 'page_1');
}


// alter view to add where clause to eliminate if nid not in group... cludgy, file issue?
// permissions + add to og + other variables?
